apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/<your-org>/enterprise-platform-configuration.git
        revision: main
        directories:
          - path: environments/dev/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        environment: dev
        team: applications
    spec:
      project: apps
      source:
        repoURL: https://github.com/<your-org>/enterprise-platform-configuration.git
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: kustomize
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
