apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/toluomoseyin/Enterprise-Platform-Configuration.git
        revision: main
        directories:
          - path: environments/staging/infra/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: infra
      source:
        repoURL: https://github.com/toluomoseyin/Enterprise-Platform-Configuration.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
