apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infra/kong/

configMapGenerator:
  - name: kong-config
    files:
      - kong.yml

generatorOptions:
  disableNameSuffixHash: true
